---
- hosts:
  - utopia
  - farpoint
  vars:
    basic_packets:
    - "htop"
    - "rsync"
    - "bmon"
    - "bash-completion"
    - "tshark"
    - "tcpdump"
    - "bridge-utils"
    - "aptitude"
    - "build-essential"
    - "ansible"
    - "dsh"
    - "emacs"
    - "etckeeper"
    - "git"
    - "ipython"
    - "ipython3"
    - "krb5-clients"
    - "links2"
    - "nmap"
    - "parted"
    - "screenie"
    - "vim"

  tasks:
  - name: Copy bashrc
    copy: src=home/bashrc dest=/root/.bashrc owner=root group=root mode=0644
  - name: Copy ssh authorized_keys
    copy: src=home/authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0644
  - name: install basic packets
    apt: pkg={{ item }} state=installed update_cache=true
    with_items: basic_packets
  - name: Install nfs file server
    apt: pkg=nfs-kernel-server state=installed update_cache=true
    notify:
    - start nfs
  - name: configure nfs default
    replace: dest=/etc/default/nfs-kernel-server regex='^RPCMOUNTDOPTS.*$' replace='RPCMOUNTDOPTS="--manage-gids --port 32767"' backup=yes
    notify:
    - restart nfs
  - name: configure nfs export
    copy: src=nfs/exports.{{ inventory_hostname }} dest=/etc/exports backup=yes owner=root group=root mode=0644
    notify:
    - restart nfs
  - name: install tftpd
    apt: pkg=tftpd-hpa state=installed update_cache=true
    notify:
    - start tftpd
    



  handlers:
  - name: start nfs
    service: name=nfs-kernel-server state=started
  - name: restart nfs
    service: name=nfs-kernel-server state=restarted
  - name: start tftpd
    service: name=tftpd-hpa state=started

