---
- hosts:
  - utopia
  - farpoint
  vars:
    basic_packets:
    - "htop"
    - "rsync"
    - "bmon"
    - "bash-completion"
    - "tshark"
    - "tcpdump"
    - "bridge-utils"
    - "aptitude"
    - "build-essential"
    - "ansible"
    - "dsh"
    - "emacs"
    - "etckeeper"
    - "git"
    - "ipython"
    - "ipython3"
    - "krb5-clients"
    - "links2"
    - "nmap"
    - "parted"
    - "screenie"
    - "vim"
    - "molly-guard"

  tasks:
  - name: Copy bashrc
    copy: src=home/bashrc dest=/root/.bashrc owner=root group=root mode=0644
  - name: Copy ssh authorized_keys
    copy: src=home/authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0644
  - name: install basic packets
    apt: pkg={{ item }} state=installed update_cache=true
    with_items: basic_packets
  - name: copy resolv.conf
    copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
  - name: Install nfs file server
    apt: pkg=nfs-kernel-server state=installed update_cache=true
  - name: configure nfs default
    replace: dest=/etc/default/nfs-kernel-server regex='^RPCMOUNTDOPTS.*$' replace='RPCMOUNTDOPTS="--manage-gids --port 32767"' backup=yes
    notify:
    - restart nfs
  - name: configure nfs export
    copy: src=nfs/exports.{{ inventory_hostname }} dest=/etc/exports backup=yes owner=root group=root mode=0644
    notify:
    - restart nfs
  - name: install tftpd
    apt: pkg=tftpd-hpa state=installed update_cache=true
    notify:
    - start tftpd
  - name: install dhcpd
    apt: pkg=isc-dhcp-server state=installed update_cache=true
  - name: configure dhcpd default
    replace: dest=/etc/default/isc-dhcp-server regex='^INTERFACES=.*$' replace='INTERFACES="etbraula etbrvirt" backup=yes
    notify:
    - restart dhcpd
  - name: configure dhcpd dhcpd.conf
    copy: src=dhcp/dhcpd.conf.{{ inventory_hostname }} dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0644 backup=yes
    notify:
    - restart dhcpd
  - name: create dhcpd groups directory
    file: path=/etc/dhcp/groups state=directory owner=root group=root mode=755
  - name: configure dhcpd client.conf
    copy: src=dhcp/client.conf dest=/etc/dhcp/groups/client.conf owner=root group=root mode=0644
    notify:
    - restart dhcpd
  - name: configure dhcpd virtual.conf
    copy: src=dhcp/virtual.conf dest=/etc/dhcp/groups/virtual.conf owner=root group=root mode=0644
    notify:
    - restart dhcpd
  - name: install cups
    apt: pkg=cups state=installed update_cache=true 
  - name: copy cups cupsd.conf
    copy: src=cups/cupsd.conf dest=/etc/cups/cupsd.conf owner=root group=root mode=0644
    notify:
    - restart cups
  - name: copy cups printers.conf
    copy: src=cups/printers.conf dest=/etc/cups/printers.conf owner=root group=lp mode=0600
    notify:
    - restart cups
  - name: create cups ppd directory
    file: path=/etc/cups/ppd state=directory owner=root group=lp mode=755
  - name: copy cups trespolo ppd
    copy: src=cups/trespolo.ppd dest=/etc/cups/ppd/trespolo.ppd owner=root group=root mode=0644
    notify:
    - restart cups
  - name: install bird
    apt: pkg=bird state=installed update_cache=true
  - name: install bird6
    apt: pkg=bird6 state=installed update_cache=true
  - name: copy bird routerid
    copy: src=bird/routerid.conf.{{ inventory_hostname }} dest=/etc/bird/routerid.conf owner=bird group=bird mode=0640
  - name: copy bird (4) bird.conf
    copy: src=bird/bird.conf dest=/etc/bird/bird.conf owner=bird group=bird mode=0640
    notify:
    - restart bird
  - name: copy bird6 bird6.conf
    copy: src=bird/bird6.conf dest=/etc/bird/bird6.conf owner=bird group=bird mode=0640
    notify:
    - restart bird6
    




  handlers:
  - name: start nfs
    service: name=nfs-kernel-server state=started
  - name: restart nfs
    service: name=nfs-kernel-server state=restarted
  - name: start tftpd
    service: name=tftpd-hpa state=started
  - name: start dhcpd
    service: name=isc-dhcp-server state=started
  - name: restart dhcpd
    service: name=isc-dhcp-server state=restarted
  - name: start cups
    service: name=cups state=started
  - name: restart cups
    service: name=cups state=restarted
  - name: restart bird
    service: name=bird state=restarted
  - name: restart bird6
    service: name=bird6 state=restarted
